### ISSUE TITLE
网页不显示

### ISSUE THREAD

**Issue by jerrychen2008** [wanglin2/code-run#2]
![image](https://user-images.githubusercontent.com/8508569/129499592-dc471ae7-ad96-4787-94a8-3ac8e24acfc1.png)
![image](https://user-images.githubusercontent.com/8508569/129499667-2e3a63d9-0fed-4375-830f-8f2d82b38fd9.png)

编译后，网页无法正常显示

**Comment by wanglin2** [comment]
当前版本应该已经修复了这个问题
