### ISSUE TITLE
求elment-plus版本

### ISSUE THREAD

**Issue by ovarte** [wanglin2/code-run#5]

**Comment by ovarte** [comment]
一直报错，试了好几个版本 
ERROR  Failed to compile with 1 error                                                                                                  15:53:29
 error  in ./node_modules/element-plus/node_modules/@popperjs/core/dist/index.js

Module parse failed: Unexpected token (1:15909)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**Comment by wanglin2** [comment]
我本地的版本是1.1.0-beta.12
