### ISSUE TITLE
有一个关于控制台显示的 bug

### ISSUE THREAD

**Issue by yucheng514** [wanglin2/code-run#7]
bug 显示如下：
<img width="643" alt="image" src="https://user-images.githubusercontent.com/35727398/180135788-8c1962fa-b5bb-47a4-abd2-3166d9e30502.png">

**Comment by wanglin2** [comment]
控制台的背景颜色是根据主题来的，有的主题的颜色是带透明度的，所以下面的textarea就显示出来了，这个暂时没想好要怎么解决
